name: Build and Release Distortion Effect

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64]   # hanya build 64-bit (paksa 64-bit)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MinGW (w64)
      run: |
        choco install mingw -y --force
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Compile Resource File
      shell: bash
      run: |
        windres malware/distortion.rc -O coff -o malware/distortion.res

    - name: Build distortion.exe (x64 only)
      shell: bash
      run: |
        g++ --version
        g++ -O2 -Wall -Wextra -static -o distortion-x64.exe malware/distortion1.cpp malware/distortion.res \
            -lwinmm -luser32 -ldwmapi -lgdi32 -lpthread -mwindows -m64

    - name: Verify build
      run: |
        Get-ChildItem *.exe
        if (-not (Test-Path "distortion-x64.exe")) {
          echo "::error::Build failed!"
          exit 1
        }

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Distortion Effect ${{ github.ref_name }}
        body: |
          INTENSE GDI DISTORTION SIMULATION v1.6
          - Effects intensify automatically over time
          - Includes particle effects, screen shake, cursor distortion
          - New effects: melting, text corruption, pixel sorting
          - Forces system shutdown on exit
          - Compatible with Windows 7/8/10/11
          - Built automatically from GitHub Actions
          - Author: WHO-AM-I-404
        files: |
          distortion-x64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
