name: Build and Release Glitch1

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install MinGW and dependencies
      run: |
        choco install mingw -y --force --version=13.2.0
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Build glitch1.exe
      run: |
        cd glitch
        g++ --version
        g++ -O3 -static -o glitch1.exe glitch1.cpp -lgdi32 -luser32 -lwinmm -lpthread -mwindows -Wl,--subsystem,windows
        
    - name: Move executable to root
      run: |
        mv glitch/glitch1.exe glitch1.exe
        
    - name: Verify build
      run: |
        if (Test-Path glitch1.exe) {
            echo "Build successful!"
            echo "File size: $((Get-Item glitch1.exe).Length) bytes"
        } else {
            echo "::error::Build failed!"
            Get-ChildItem
            exit 1
        }

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Glitch1 ${{ github.ref_name }}
        body: |
          GLITCH1 SIMULATION
          - Effects intensify automatically over time
          - Includes particle effects, screen shake, and cursor distortion
          - Forces system shutdown on exit
          - Compatible with Windows 7/8/10/11
          - Built automatically from GitHub Actions
        files: glitch1.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
