name: Build and Release Glitch

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Find MinGW
      run: |
        # Cari lokasi g++ di sistem
        $gppPath = (Get-Command g++ -ErrorAction SilentlyContinue).Path
        if ($gppPath) {
            $mingwBin = Split-Path -Path $gppPath -Parent
            echo "Found MinGW at: $mingwBin"
            echo "$mingwBin" | Out-File -FilePath $env:GITHUB_PATH -Append
        } else {
            echo "::error::MinGW not found! Installing via Chocolatey..."
            choco install mingw --version=13.2.0 --yes
            echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        }

    - name: Build glitch.exe
      run: |
        g++ --version
        g++ -O2 -static -o glitch.exe glitch.cpp -lgdi32

    - name: Verify build
      run: |
        if (Test-Path glitch.exe) {
            echo "Build successful!"
            echo "File size: $((Get-Item glitch.exe).Length) bytes"
        } else {
            echo "Build failed!"
            Get-ChildItem
            exit 1
        }

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Glitch Effect ${{ github.ref_name }}
        body: |
          Desktop glitch effect application
          - Press ESC to exit
          - Built automatically from GitHub Actions
        files: glitch.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
