name: Build and Release Extreme Glitch

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install MinGW and dependencies
      run: |
        choco install mingw -y --force --version=13.2.0
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Build glitch.exe
      run: |
        g++ --version
        g++ -O3 -static -o glitch.exe glitch.cpp -lgdi32 -luser32 -lwinmm -lpthread

    - name: Verify build
      run: |
        if (Test-Path glitch.exe) {
            echo "Build successful!"
            echo "File size: $((Get-Item glitch.exe).Length) bytes"
        } else {
            echo "::error::Build failed!"
            Get-ChildItem
            exit 1
        }

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Extreme Glitch ${{ github.ref_name }}
        body: |
          Ultimate desktop glitch effect with intense visuals and sound
          - Press ESC to exit
          - Press S to toggle sound
          - System-safe: No permanent changes
          - Built automatically from GitHub Actions
        files: glitch.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
