name: Build Release

on:
  push:
    tags:
      - 'v1.0'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MinGW
      run: |
        choco install mingw -y
        
    - name: Set PATH for MinGW
      run: |
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build distortion.exe
      run: |
        gcc -O3 -o destortion.exe destortion.c -lgdi32 -lm

    - name: Create Release Artifact
      run: |
        7z a DistortionEffect-v1.0-windows.zip destortion.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DistortionEffect-v1.0
        path: DistortionEffect-v1.0-windows.zip
