name: Build Release

on:
  push:
    tags:
      - 'v1.0'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MinGW
      uses: mingw-actions/setup-mingw@v2
      with:
        version: '12.2.0'
        architecture: 'x86_64'

    - name: Build distortion.exe
      run: |
        gcc -O3 -o distortion.exe distortion.c -lgdi32 -lm

    - name: Create Release Artifact
      run: |
        7z a DistortionEffect-v1.0-windows.zip distortion.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DistortionEffect-v1.0
        path: DistortionEffect-v1.0-windows.zip
