name: Build and Release MEMZ-Style Glitch

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install MinGW and dependencies
      run: |
        choco install mingw -y --force --version=13.2.0
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Build memz_glitch.exe
      run: |
        cd glitch
        g++ --version
        g++ -O3 -static -o memz_glitch.exe glitch1.cpp -lgdi32 -luser32 -lwinmm -lpthread -mwindows
        
    - name: Move executable to root
      run: |
        mv glitch/memz_glitch.exe memz_glitch.exe
        
    - name: Verify build
      run: |
        if (Test-Path memz_glitch.exe) {
            echo "Build successful!"
            echo "File size: $((Get-Item memz_glitch.exe).Length) bytes"
        } else {
            echo "::error::Build failed!"
            Get-ChildItem
            exit 1
        }

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: MEMZ-Style Glitch ${{ github.ref_name }}
        body: |
          EXTREME SYSTEM GLITCH SIMULATION (MEMZ-STYLE)
          - Press ESC to exit
          - Effects intensify automatically over time
          - Includes particle effects, screen shake, and cursor distortion
          - No permanent system changes
          - Built automatically from GitHub Actions
        files: memz_glitch.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
