name: Build and Release Distortion Effect

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MinGW (w64)
      run: |
        choco install mingw -y --force
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Build distortion.exe (${{ matrix.arch }})
      shell: bash
      run: |
        g++ --version
        if [ "${{ matrix.arch }}" = "x86" ]; then
          g++ -O2 -Wall -Wextra -static -o distortion-x86.exe distortion1.cpp \
              -lwinmm -luser32 -ldwmapi -lgdi32 -lpthread -mwindows -m32
        else
          g++ -O2 -Wall -Wextra -static -o distortion-x64.exe distortion1.cpp \
              -lwinmm -luser32 -ldwmapi -lgdi32 -lpthread -mwindows -m64
        fi

    - name: Verify build
      run: |
        Get-ChildItem *.exe
        if (-not (Test-Path "distortion-${{ matrix.arch }}.exe")) {
          echo "::error::Build failed!"
          exit 1
        }

    - name: Create GitHub Release
      if: matrix.arch == 'x64'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Distortion Effect ${{ github.ref_name }}
        body: |
          INTENSE GDI DISTORTION SIMULATION
          - Effects intensify automatically over time
          - Includes particle effects, screen shake, cursor distortion
          - New effects: melting, text corruption, pixel sorting
          - Forces system shutdown on exit
          - Compatible with Windows 7/8/10/11
          - Built automatically from GitHub Actions
        files: |
          distortion-x86.exe
          distortion-x64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
